set_property IOSTANDARD LVCMOS33 [get_ports {black[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {black[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {black[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {black[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports h_sync]
set_property IOSTANDARD LVCMOS33 [get_ports v_sync]
set_property PACKAGE_PIN N19 [get_ports {black[3]}]
set_property PACKAGE_PIN J19 [get_ports {black[2]}]
set_property PACKAGE_PIN H19 [get_ports {black[1]}]
set_property PACKAGE_PIN G19 [get_ports {black[0]}]
set_property PACKAGE_PIN D17 [get_ports {green[3]}]
set_property PACKAGE_PIN G17 [get_ports {green[2]}]
set_property PACKAGE_PIN H17 [get_ports {green[1]}]
set_property PACKAGE_PIN J17 [get_ports {green[0]}]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN P19 [get_ports h_sync]
set_property PACKAGE_PIN R19 [get_ports v_sync]

set_property IOSTANDARD LVCMOS33 [get_ports {blue[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[0]}]
set_property PACKAGE_PIN N18 [get_ports {blue[0]}]
set_property PACKAGE_PIN L18 [get_ports {blue[1]}]
set_property PACKAGE_PIN K18 [get_ports {blue[2]}]
set_property PACKAGE_PIN J18 [get_ports {blue[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports gameState]
set_property PACKAGE_PIN V17 [get_ports gameState]


set_property PACKAGE_PIN R2 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

set_property IOSTANDARD LVCMOS33 [get_ports {user_input[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {user_input[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {user_input[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {user_input[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {user_input[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {user_input[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {user_input[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {user_input[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {user_input[0]}]
set_property PACKAGE_PIN T1 [get_ports {user_input[8]}]
set_property PACKAGE_PIN U1 [get_ports {user_input[7]}]
set_property PACKAGE_PIN W2 [get_ports {user_input[6]}]
set_property PACKAGE_PIN R3 [get_ports {user_input[5]}]
set_property PACKAGE_PIN T2 [get_ports {user_input[4]}]
set_property PACKAGE_PIN T3 [get_ports {user_input[3]}]
set_property PACKAGE_PIN V2 [get_ports {user_input[2]}]
set_property PACKAGE_PIN W13 [get_ports {user_input[1]}]
set_property PACKAGE_PIN W14 [get_ports {user_input[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {lifeLED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lifeLED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lifeLED[0]}]
set_property PACKAGE_PIN L1 [get_ports {lifeLED[2]}]
set_property PACKAGE_PIN P1 [get_ports {lifeLED[1]}]
set_property PACKAGE_PIN N3 [get_ports {lifeLED[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports CC]
set_property IOSTANDARD LVCMOS33 [get_ports CA]
set_property IOSTANDARD LVCMOS33 [get_ports CB]
set_property IOSTANDARD LVCMOS33 [get_ports CD]
set_property IOSTANDARD LVCMOS33 [get_ports CE]
set_property IOSTANDARD LVCMOS33 [get_ports CF]
set_property IOSTANDARD LVCMOS33 [get_ports CG]
set_property PACKAGE_PIN W7 [get_ports CA]
set_property PACKAGE_PIN W6 [get_ports CB]
set_property PACKAGE_PIN U8 [get_ports CC]
set_property PACKAGE_PIN V8 [get_ports CD]
set_property PACKAGE_PIN U5 [get_ports CE]
set_property PACKAGE_PIN V5 [get_ports CF]
set_property PACKAGE_PIN U7 [get_ports CG]


set_property IOSTANDARD LVCMOS33 [get_ports {sevenseg_enable[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sevenseg_enable[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sevenseg_enable[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sevenseg_enable[0]}]
set_property PACKAGE_PIN U2 [get_ports {sevenseg_enable[3]}]
set_property PACKAGE_PIN U4 [get_ports {sevenseg_enable[2]}]
set_property PACKAGE_PIN V4 [get_ports {sevenseg_enable[1]}]
set_property PACKAGE_PIN W4 [get_ports {sevenseg_enable[0]}]
